apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ai-dev-asst
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - ai-dev-asst-client.southindia.cloudapp.azure.com
      secretName: ai-dev-asst-tls
  rules:
    - host: ai-dev-asst-client.southindia.cloudapp.azure.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: ai-dev-asst-api
                port:
                  name: http
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ai-dev-asst-client
                port:
                  name: http
